version: '3.8'
services:
  postgres:
    image: 'postgres:15.2'
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ../go-form-builder-db/data:/var/lib/postgressql/data  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080